nrrg:
  bwp:
    bwpcp:
    - normal
    - normal
    - normal
    - normal
    bwpid:
    - 0
    - 1
    - 0
    - 1
    bwplocandbw:
    - 12925
    - 1099
    - 1099
    - 1099
    bwpnumrbs:
    - 48
    - 273
    - 273
    - 273
    bwpscs:
    - 30KHz
    - 30KHz
    - 30KHz
    - 30KHz
    bwpstartrb:
    - 0
    - 0
    - 0
    - 0
    bwptype:
    - iniDlBwp
    - dedDlBwp
    - iniUlBwp
    - dedUlBwp
  carriergrid:
    bw: 100MHz
    carriernumrbs: 273
    carrierscs: 30KHz
    offsettocarrier: 0
  commonsetting:
    numueap: 2T
    patnumdlslots:
    - 7
    patnumdlsymbs:
    - 6
    patnumulslots:
    - 2
    patnumulsymbs:
    - 4
    patperiod:
    - 5ms
    pci: 0
    refscs: 30KHz
  coreset1:
    coreset1cceregmap: interleaved
    coreset1duration: 1
    coreset1freqres: "111111111111111111111111111111111111111111111"
    coreset1interleaversize: n2
    coreset1regbundlesize: n2
    coreset1shiftind: 0
  css0:
    css0agglevel: 4
    css0numcandidates: n4
  dci01:
    actbwp: 1
    dci01antports: 0
    dci01cbtpminumlayers: 2
    dci01fdfreqhop: disabled
    dci01fdnumrbs: 273
    dci01fdra: "0000001000100001"
    dci01fdratype: raType1
    dci01fdstartrb: 0
    dci01mcscw0: 28
    dci01ptrsdmrsmap: 0
    dci01sri: ""
    dci01tdk2: 1
    dci01tdmappingtype: typeA
    dci01tdnumsymbs: 14
    dci01tdra: 16
    dci01tdsliv: 27
    dci01tdstartsymb: 0
    indicatedbwp: 1
    mupdcch: 1
    mupusch: 1
    rnti: C-RNTI
    tbs: 475584
  dci10:
    dci10fdnumrbs:
    - 48
    - 48
    - 48
    dci10fdstartrb:
    - 0
    - 0
    - 0
    dci10fdvrbprbmappingtype:
    - interleaved
    - interleaved
    - interleaved
    dci10mcscw0:
    - 2
    - 2
    - 2
    dci10msg2tbscaling: 0
    dci10msg4deltapri: 1
    dci10msg4tdk1: 6
    dci10tdra:
    - 10
    - 10
    - 10
    fdbundlesize:
    - n2
    - n2
    - n2
    fdra:
    - "00001011111"
    - "00001011111"
    - "00001011111"
    fdratype:
    - raType1
    - raType1
    - raType1
    mupdcch:
    - 1
    - 1
    - 1
    mupdsch:
    - 1
    - 1
    - 1
    rnti:
    - SI-RNTI
    - RA-RNTI
    - TC-RNTI
    tbs:
    - 408
    - 408
    - 408
    tdk0:
    - 0
    - 0
    - 0
    tdmappingtype:
    - typeB
    - typeB
    - typeB
    tdnumsymbs:
    - 2
    - 2
    - 2
    tdsliv:
    - 26
    - 26
    - 26
    tdstartsymb:
    - 12
    - 12
    - 12
  dci11:
    actbwp: 1
    dci11antports: 10
    dci11deltapri: 1
    dci11fdbundlesize: n2
    dci11fdnumrbs: 273
    dci11fdra: "0000001000100001"
    dci11fdratype: raType1
    dci11fdstartrb: 0
    dci11fdvrbprbmappingtype: interleaved
    dci11mcscw0: 27
    dci11mcscw1: -1
    dci11tdk0: 0
    dci11tdk1: 2
    dci11tdmappingtype: typeA
    dci11tdnumsymbs: 14
    dci11tdra: 16
    dci11tdsliv: 27
    dci11tdstartsymb: 0
    indicatedbwp: 1
    mupdcch: 1
    mupdsch: 1
    rnti: C-RNTI
    tbs: 1277992
  dmrscommon:
    cdmgroupswodata:
    - 1
    - 1
    - 1
    - 2
    dmrsaddpos:
    - pos0
    - pos0
    - pos0
    - pos1
    dmrsports:
    - 1000
    - 1000
    - 1000
    - 0
    dmrstype:
    - type1
    - type1
    - type1
    - type1
    fdk:
    - "101010101010"
    - "101010101010"
    - "101010101010"
    - "111111111111"
    maxlength:
    - len1
    - len1
    - len1
    - len1
    numfrontloadsymbs:
    - 1
    - 1
    - 1
    - 1
    schinfo:
    - SIB1
    - Msg2
    - Msg4
    - Msg3
    tdl:
    - "0"
    - "0"
    - "0"
    - "0:0"
  dmrspdsch:
    cdmgroupswodata: 2
    dmrsports:
    - 1000
    - 1001
    - 1002
    - 1003
    fdk: "111111111111"
    numfrontloadsymbs: 1
    pdschdmrsaddpos: pos0
    pdschdmrstype: type1
    pdschmaxlength: len1
    tdl: "2"
  dmrspusch:
    cdmgroupswodata: 1
    dmrsports:
    - 0
    - 1
    fdk: "101010101010"
    numfrontloadsymbs: 1
    puschdmrsaddpos: pos0
    puschdmrstype: type1
    puschmaxlength: len1
    tdl: "2"
  freqband:
    duplexmode: TDD
    freqrange: FR1
    maxdlfreq: 2690
    opband: n41
  mib:
    commonscs: 30KHz
    coreset0multiplexingpat: 1
    coreset0numrbs: 48
    coreset0numsymbs: 1
    coreset0offset: 16
    coreset0offsetlist:
    - 16
    dmrstypeapos: pos2
    hrf: 0
    rmsicoreset0: 12
    rmsicss0: 0
    sfn: 0
  msg3:
    fdratype: raType1
    fdsecondhopfreqoff: 68
    msg3fdfreqhop: enabled
    msg3fdnumrbs: 62
    msg3fdra: "0100000100001101"
    msg3fdstartrb: 0
    msg3mcscw0: 2
    msg3tdra: 6
    mupusch: 1
    tbs: 1544
    tddelta: 3
    tdk2: 1
    tdmappingtype: typeB
    tdnumsymbs: 6
    tdsliv: 74
    tdstartsymb: 4
  ptrspdsch:
    dmrsports:
    - 1000
    pdschptrsenabled: true
    pdschptrsfreqdensity: 2
    pdschptrsreoffset: offset00
    pdschptrstimedensity: 1
  ptrspusch:
    dmrsports:
    - 1000
    dmrsportstp: []
    numgrpstp: 2
    puschptrsenabled: true
    puschptrsfreqdensity: 2
    puschptrsgrppatterntp: p0
    puschptrsmaxnumports: n1
    puschptrsreoffset: offset00
    puschptrstimedensity: 1
    puschptrstimedensitytp: 1
    samplespergrptp: 2
  rach:
    cbpreambsperssb: 64
    contrestimer: sf64
    msg1fdm: 1
    msg1freqstart: 0
    msg1scs: 30KHz
    msg3tp: disabled
    prachconfid: 148
    raduration: 12
    raformat: B4
    rakbar: 2
    ralen: 139
    ranumoccasionsperslot: 1
    ranumrbs: 12
    ranumslotspersubffr1per60kslotfr2: 1
    rarespwin: sl20
    rastartingsymb: 0
    rasubfnumfr1slotnumfr2:
    - 9
    rax: 2
    ray:
    - 1
    ssbperrachoccasion: one
    totnumpreambs: 64
  ssbburst:
    grouppresence: ""
    inonegroup: "11111111"
    maxl: 8
    ssbperiod: 20ms
  ssbgrid:
    kssb: 0
    ncrbssb: 32
    ssbpattern: Case C
    ssbscs: 30KHz
  uss:
    ussagglevel: 4
    ussduration: 1
    ussfirstsymbs: "10101010101010"
    ussnumcandidates: n1
    ussoffset: 0
    ussperiod: sl1
tti:
  dir: ""
