nrrg:
  bwp:
    _bwpcp:
    - normal
    - normal
    - normal
    - normal
    _bwpid:
    - 0
    - 1
    - 0
    - 1
    _bwpscs:
    - 30KHz
    - 30KHz
    - 30KHz
    - 30KHz
    _bwptype:
    - iniDlBwp
    - dedDlBwp
    - iniUlBwp
    - dedUlBwp
    bwplocandbw:
    - 12925
    - 1099
    - 1099
    - 1099
    bwpnumrbs:
    - 48
    - 273
    - 273
    - 273
    bwpstartrb:
    - 0
    - 0
    - 0
    - 0
  carriergrid:
    _carriernumrbs: 273
    _offsettocarrier: 0
    bw: 100MHz
    carrierscs: 30KHz
  commonsetting:
    _refscs: 30KHz
    numueap: 2T
    patnumdlslots:
    - 7
    patnumdlsymbs:
    - 6
    patnumulslots:
    - 2
    patnumulsymbs:
    - 4
    patperiod:
    - 5ms
    pci: 0
  coreset1:
    coreset1cceregmap: interleaved
    coreset1duration: 1
    coreset1freqres: "111111111111111111111111111111111111111111111"
    coreset1interleaversize: n2
    coreset1regbundlesize: n2
    coreset1shiftind: 0
  css0:
    css0agglevel: 4
    css0numcandidates: n4
  dci01:
    _actbwp: 1
    _indicatedbwp: 1
    _mupdcch: 1
    _mupusch: 1
    _rnti: C-RNTI
    _tbs: 475584
    dci01antports: 0
    dci01cbtpminumlayers: 2
    dci01fdfreqhop: disabled
    dci01fdnumrbs: 273
    dci01fdra: "0000001000100001"
    dci01fdratype: raType1
    dci01fdstartrb: 0
    dci01mcscw0: 28
    dci01ptrsdmrsmap: 0
    dci01sri: ""
    dci01tdk2: 1
    dci01tdmappingtype: typeA
    dci01tdnumsymbs: 14
    dci01tdra: 16
    dci01tdsliv: 27
    dci01tdstartsymb: 0
  dci10:
    _fdbundlesize:
    - n2
    - n2
    - n2
    _fdra:
    - "00001011111"
    - "00001011111"
    - "00001011111"
    _fdratype:
    - raType1
    - raType1
    - raType1
    _mupdcch:
    - 1
    - 1
    - 1
    _mupdsch:
    - 1
    - 1
    - 1
    _rnti:
    - SI-RNTI
    - RA-RNTI
    - TC-RNTI
    _tbs:
    - 408
    - 408
    - 408
    _tdk0:
    - 0
    - 0
    - 0
    _tdmappingtype:
    - typeB
    - typeB
    - typeB
    _tdnumsymbs:
    - 2
    - 2
    - 2
    _tdsliv:
    - 26
    - 26
    - 26
    _tdstartsymb:
    - 12
    - 12
    - 12
    dci10fdnumrbs:
    - 48
    - 48
    - 48
    dci10fdstartrb:
    - 0
    - 0
    - 0
    dci10fdvrbprbmappingtype:
    - interleaved
    - interleaved
    - interleaved
    dci10mcscw0:
    - 2
    - 2
    - 2
    dci10msg2tbscaling: 0
    dci10msg4deltapri: 1
    dci10msg4tdk1: 6
    dci10tdra:
    - 10
    - 10
    - 10
  dci11:
    _actbwp: 1
    _indicatedbwp: 1
    _mupdcch: 1
    _mupdsch: 1
    _rnti: C-RNTI
    _tbs: 1277992
    dci11antports: 10
    dci11deltapri: 1
    dci11fdbundlesize: n2
    dci11fdnumrbs: 273
    dci11fdra: "0000001000100001"
    dci11fdratype: raType1
    dci11fdstartrb: 0
    dci11fdvrbprbmappingtype: interleaved
    dci11mcscw0: 27
    dci11mcscw1: -1
    dci11tdk0: 0
    dci11tdk1: 2
    dci11tdmappingtype: typeA
    dci11tdnumsymbs: 14
    dci11tdra: 16
    dci11tdsliv: 27
    dci11tdstartsymb: 0
  dmrscommon:
    _cdmgroupswodata:
    - 1
    - 1
    - 1
    - 2
    _dmrsaddpos:
    - pos0
    - pos0
    - pos0
    - pos1
    _dmrsports:
    - 1000
    - 1000
    - 1000
    - 0
    _dmrstype:
    - type1
    - type1
    - type1
    - type1
    _fdk:
    - "101010101010"
    - "101010101010"
    - "101010101010"
    - "111111111111"
    _maxlength:
    - len1
    - len1
    - len1
    - len1
    _numfrontloadsymbs:
    - 1
    - 1
    - 1
    - 1
    _schinfo:
    - SIB1
    - Msg2
    - Msg4
    - Msg3
    _tdl:
    - "0"
    - "0"
    - "0"
    - "0_0"
  dmrspdsch:
    _cdmgroupswodata: 2
    _dmrsports:
    - 1000
    - 1001
    - 1002
    - 1003
    _fdk: "111111111111"
    _numfrontloadsymbs: 1
    _tdl: "2"
    pdschdmrsaddpos: pos0
    pdschdmrstype: type1
    pdschmaxlength: len1
  dmrspusch:
    _cdmgroupswodata: 1
    _dmrsports:
    - 0
    - 1
    _fdk: "101010101010"
    _numfrontloadsymbs: 1
    _tdl: "2"
    puschdmrsaddpos: pos0
    puschdmrstype: type1
    puschmaxlength: len1
  freqband:
    _duplexmode: TDD
    _freqrange: FR1
    _maxdlfreq: 2690
    opband: n41
  mib:
    _coreset0multiplexingpat: 1
    _coreset0numrbs: 48
    _coreset0numsymbs: 1
    _coreset0offset: 16
    _coreset0offsetlist:
    - 16
    commonscs: 30KHz
    dmrstypeapos: pos2
    hrf: 0
    rmsicoreset0: 12
    rmsicss0: 0
    sfn: 0
  msg3:
    _fdratype: raType1
    _fdsecondhopfreqoff: 68
    _mupusch: 1
    _tbs: 1544
    _tddelta: 3
    _tdk2: 1
    _tdmappingtype: typeB
    _tdnumsymbs: 6
    _tdsliv: 74
    _tdstartsymb: 4
    msg3fdfreqhop: enabled
    msg3fdnumrbs: 62
    msg3fdra: "0100000100001101"
    msg3fdstartrb: 0
    msg3mcscw0: 2
    msg3tdra: 6
  nzpcsirs:
    _cdmgrpindj:
    - 0
    - 1
    _kap:
    - 0
    - 1
    _kbarlbar:
    - 0,0
    - 2,0
    _ki:
    - 0
    - 0
    _lap:
    - 0
    _li:
    - 0
    - 0
    _resid: 0
    _ressetid: 0
    _row: 4
    _trsinfo: false
    nzpcsirscdmtype: fd-CDM2
    nzpcsirsdensity: one
    nzpcsirsfirstsymb: 1
    nzpcsirsfirstsymb2: -1
    nzpcsirsfreqallocbits: "001"
    nzpcsirsfreqallocrow: row4
    nzpcsirsnumports: p4
    nzpcsirsnumrbs: 276
    nzpcsirsoffset: 10
    nzpcsirsperiod: slots20
    nzpcsirsstartrb: 0
  pdsch:
    _rbgsize: 16
    pdschaggfactor: n1
    pdschmcstable: qam256
    pdschrbgcfg: config1
    pdschxoh: xOh0
  ptrspdsch:
    _dmrsports:
    - 1000
    pdschptrsenabled: true
    pdschptrsfreqdensity: 2
    pdschptrsreoffset: offset00
    pdschptrstimedensity: 1
  ptrspusch:
    _dmrsports:
    - 0
    _dmrsportstp: []
    _numgrpstp: 2
    _samplespergrptp: 2
    puschptrsenabled: true
    puschptrsfreqdensity: 2
    puschptrsgrppatterntp: p0
    puschptrsmaxnumports: n1
    puschptrsreoffset: offset00
    puschptrstimedensity: 1
    puschptrstimedensitytp: 1
  pusch:
    _rbgsize: 16
    puschaggfactor: n1
    puschcbmaxranknoncbmaxlayers: 2
    puschcbsubset: fullyAndPartialAndNonCoherent
    puschfreqhopoffset: 0
    puschmcstable: qam64
    puschrbgcfg: config1
    puschtp: disabled
    puschtxcfg: codebook
    puschxoh: xOh0
  rach:
    _raduration: 12
    _raformat: B4
    _rakbar: 2
    _ralen: 139
    _ranumoccasionsperslot: 1
    _ranumrbs: 12
    _ranumslotspersubffr1per60kslotfr2: 1
    _rastartingsymb: 0
    _rasubfnumfr1slotnumfr2:
    - 9
    _rax: 2
    _ray:
    - 1
    cbpreambsperssb: 64
    contrestimer: sf64
    msg1fdm: 1
    msg1freqstart: 0
    msg1scs: 30KHz
    msg3tp: disabled
    prachconfid: 148
    rarespwin: sl20
    ssbperrachoccasion: one
    totnumpreambs: 64
  ssbburst:
    _maxl: 8
    grouppresence: ""
    inonegroup: "11111111"
    ssbperiod: 20ms
  ssbgrid:
    _ncrbssb: 32
    _ssbpattern: Case C
    kssb: 0
    ssbscs: 30KHz
  uss:
    ussagglevel: 4
    ussduration: 1
    ussfirstsymbs: "10101010101010"
    ussnumcandidates: n1
    ussoffset: 0
    ussperiod: sl1
tti:
  dir: ./data
