nrrg:
  carriergrid:
    bw: 100MHz
    carriernumrbs: 273
    carrierscs: 30KHz
    offsettocarrier: 0
  commonsetting:
    numueap: 2T
    patnumdlslots:
    - 7
    patnumdlsymbs:
    - 6
    patnumulslots:
    - 2
    patnumulsymbs:
    - 4
    patperiod:
    - 5ms
    pci: 0
    refscs: 30KHz
  coreset1:
    coreset1cceregmap: interleaved
    coreset1duration: 1
    coreset1freqres: "111111111111111111111111111111111111111111111"
    coreset1interleaversize: n2
    coreset1regbundlesize: n2
    coreset1shiftind: 0
  css0:
    css0agglevel: 4
    css0numcandidates: n4
  dci01:
    actbwp: 1
    dci01antports: 0
    dci01cbtpminumlayers: 2
    dci01fdfreqhop: disabled
    dci01fdnumrbs: 273
    dci01fdra: "0000001000100001"
    dci01fdratype: raType1
    dci01fdstartrb: 0
    dci01mcscw0: 28
    dci01ptrsdmrsmap: 0
    dci01sri: ""
    dci01tdk2: 1
    dci01tdmappingtype: typeA
    dci01tdnumsymbs: 14
    dci01tdra: 16
    dci01tdsliv: 27
    dci01tdstartsymb: 0
    indicatedbwp: 1
    mupdcch: 1
    mupusch: 1
    rnti: C-RNTI
    tbs: 475584
  dci10:
    dci10fdnumrbs:
    - 48
    - 48
    - 48
    dci10fdstartrb:
    - 0
    - 0
    - 0
    dci10fdvrbprbmappingtype:
    - interleaved
    - interleaved
    - interleaved
    dci10mcscw0:
    - 2
    - 2
    - 2
    dci10msg2tbscaling: 0
    dci10msg4deltapri: 1
    dci10msg4tdk1: 6
    dci10tdra:
    - 10
    - 10
    - 10
    fdbundlesize:
    - n2
    - n2
    - n2
    fdra:
    - "00001011111"
    - "00001011111"
    - "00001011111"
    fdratype:
    - raType1
    - raType1
    - raType1
    mupdcch:
    - 1
    - 1
    - 1
    mupdsch:
    - 1
    - 1
    - 1
    rnti:
    - SI-RNTI
    - RA-RNTI
    - TC-RNTI
    tbs:
    - 408
    - 408
    - 408
    tdk0:
    - 0
    - 0
    - 0
    tdmappingtype:
    - typeB
    - typeB
    - typeB
    tdnumsymbs:
    - 2
    - 2
    - 2
    tdsliv:
    - 26
    - 26
    - 26
    tdstartsymb:
    - 12
    - 12
    - 12
  dci11:
    actbwp: 1
    dci11antports: 10
    dci11deltapri: 1
    dci11fdbundlesize: n2
    dci11fdnumrbs: 273
    dci11fdra: "0000001000100001"
    dci11fdratype: raType1
    dci11fdstartrb: 0
    dci11fdvrbprbmappingtype: interleaved
    dci11mcscw0: 27
    dci11mcscw1: -1
    dci11tdk0: 0
    dci11tdk1: 2
    dci11tdmappingtype: typeA
    dci11tdnumsymbs: 14
    dci11tdra: 16
    dci11tdsliv: 27
    dci11tdstartsymb: 0
    indicatedbwp: 1
    mupdcch: 1
    mupdsch: 1
    rnti: C-RNTI
    tbs: 1277992
  freqband:
    duplexmode: TDD
    freqrange: FR1
    maxdlfreq: 2690
    opband: n41
  mib:
    commonscs: 30KHz
    coreset0multiplexingpat: 1
    coreset0numrbs: 48
    coreset0numsymbs: 1
    coreset0offset: 16
    coreset0offsetlist:
    - 16
    dmrstypeapos: pos2
    hrf: 0
    rmsicoreset0: 12
    rmsicss0: 0
    sfn: 0
  msg3:
    fdratype: raType1
    fdsecondhopfreqoff: 68
    msg3fdfreqhop: enabled
    msg3fdnumrbs: 62
    msg3fdra: "0100000100001101"
    msg3fdstartrb: 0
    msg3mcscw0: 2
    msg3tdra: 6
    mupusch: 1
    tbs: 1544
    tddelta: 3
    tdk2: 1
    tdmappingtype: typeB
    tdnumsymbs: 6
    tdsliv: 74
    tdstartsymb: 4
  ssbburst:
    grouppresence: ""
    inonegroup: "11111111"
    maxl: 8
    ssbperiod: 20ms
  ssbgrid:
    kssb: 0
    ncrbssb: 32
    ssbpattern: Case C
    ssbscs: 30KHz
  uss:
    ussagglevel: 4
    ussduration: 1
    ussfirstsymbs: "10101010101010"
    ussnumcandidates: n1
    ussoffset: 0
    ussperiod: sl1
tti:
  dir: ""
